Switch to agent download via API token, Removed obsolete package

diff --git a/jobs/dynatrace-oneagent/templates/dynatrace-oneagent.sh.erb b/jobs/dynatrace-oneagent/templates/dynatrace-oneagent.sh.erb
--- a/jobs/dynatrace-oneagent/templates/dynatrace-oneagent.sh.erb
+++ b/jobs/dynatrace-oneagent/templates/dynatrace-oneagent.sh.erb
@@ -3,23 +3,43 @@ set -e -x
 
 export PATH="/var/vcap/packages/dynatrace-oneagent:$PATH"
 
-export PROXY=<%= properties.dynatrace.proxy %>
 export DOWNLOADURL=<%= properties.dynatrace.downloadurl %>
-export PROCESSHOOKING=<%= properties.dynatrace.processhooking %>
+export PROXY=<%= properties.dynatrace.proxy %>
+export ENV_ID=<%= properties.dynatrace.environmentid %>
+export API_TOKEN=<%= properties.dynatrace.apitoken %>
+export API_URL=<%= properties.dynatrace.apiurl %>
+export SSL_MODE=<%= properties.dynatrace.sslmode %>
 export APP_LOG_CONTENT_ACCESS=<%= properties.dynatrace.applogaccess %>
+
 export TMPDIR=/var/vcap/data/tmp
 
 ARGS=""
 if [ "$PROXY" != "" ]; then
   ARGS="$ARGS PROXY=$PROXY"
 fi
-if [ "$PROCESSHOOKING" != "" ]; then
-  ARGS="$ARGS PROCESSHOOKING=$PROCESSHOOKING"
-fi
+
 if [ "$APP_LOG_CONTENT_ACCESS" != "" ]; then
   ARGS="$ARGS APP_LOG_CONTENT_ACCESS=$APP_LOG_CONTENT_ACCESS"
 fi
 
+# set downloadurl if not given
+if [ "$DOWNLOADURL" == "" ]; then
+  if [ "x$ENV_ID" == "x" ] && [ "x$API_TOKEN" == "x" ]; then
+    echo "Invalid configuration:"
+    echo "Please set environment ID and API token for Dynatrace OneAgent."
+    exit 1
+  fi
+  if [ "x$API_URL" == "x" ]; then
+    API_URL="https://$ENV_ID.live.dynatrace.com/api"
+  fi
+  DOWNLOADURL="$API_URL/v1/deployment/installer/agent/unix/default/latest?Api-Token=$API_TOKEN"
+fi
+
+SSL_FLAG=""
+if [ "$SSL_MODE" == "all" ]; then
+  echo "accepting all ssl certificates for agent download"
+  SSL_FLAG="--insecure"
+fi
 
 RUN_DIR=/var/vcap/sys/run/dynatrace-oneagent
 LOG_DIR=/var/vcap/sys/log/dynatrace-oneagent
@@ -29,9 +49,7 @@ mkdir -p ${RUN_DIR} ${LOG_DIR}
 getInstallDir() {
         local INSTALL_DIR="/opt/dynatrace/oneagent"
 
-        if [ -d /var/vcap/store ] && [ $(df --output=avail -m /var/vcap/store | sed 1d) -gt 2048 ]; then
-          INSTALL_DIR="/var/vcap/store/dynatrace/oneagent"
-        elif [ -d /var/vcap/data ] && [ $(df --output=avail -m /var/vcap/data | sed 1d) -gt 2048 ]; then
+        if [ -d /var/vcap/data ] && [ $(df --output=avail -m /var/vcap/data | sed 1d) -gt 2048 ]; then
           INSTALL_DIR="/var/vcap/data/dynatrace/oneagent"
         fi
 
@@ -53,7 +71,7 @@ case $1 in
     # If the watchdog was stopped or rolled over...
     if [ "$pid" == "" ]; then
       mkdir -p $TMPDIR
-      curl -L -k -o $TMPDIR/Dynatrace-OneAgent-Linux.sh $DOWNLOADURL
+      curl -L $SSL_FLAG -o $TMPDIR/Dynatrace-OneAgent-Linux.sh $DOWNLOADURL
       chmod 755 $TMPDIR/Dynatrace-OneAgent-Linux.sh
       install_path=$(getInstallDir)
 
